# This Dockerfile runs the RouteGuide server from
# https://grpc.io/docs/tutorials/basic/python.html

FROM docker.io/library/python:3.10.6-slim
RUN pip install grpcio-tools
ADD https://github.com/grpc/grpc/archive/v1.14.x.tar.gz .
RUN tar -zxvf v1.14.x.tar.gz
WORKDIR grpc-1.14.x/examples/python/route_guide

EXPOSE 50051
CMD ["python", "route_guide_server.py"]
