# This Dockerfile runs the RouteGuide server from
# https://grpc.io/docs/tutorials/basic/python.html

FROM docker.io/library/python:3.12.0-slim
RUN pip install grpcio-tools
ARG TAG=1.56.x
ADD https://github.com/grpc/grpc/archive/v${TAG}.tar.gz .
RUN tar -zxvf v${TAG}.tar.gz
WORKDIR grpc-${TAG}/examples/python/route_guide

EXPOSE 50051
CMD ["python", "route_guide_server.py"]
