# This Dockerfile runs the helloworld server from
# https://grpc.io/docs/quickstart/go.html

FROM docker.io/library/golang:1.19.0-alpine
ADD https://github.com/grpc/grpc-go/archive/v1.48.0.tar.gz .
RUN tar -zxvf v1.48.0.tar.gz
WORKDIR grpc-go-1.48.0/examples/helloworld

EXPOSE 50051
CMD ["go", "run", "greeter_server/main.go"]